### ISSUE TITLE
Not working with factory girl gem

### ISSUE THREAD

**Issue by devilankur18** [palkan/logidze#9]
Its working fine in development and production mode. But when running in testing where factory_girl gem is loaded, it casing errors. Check the stack for more details.

```
undefined local variable or method `has_logidze' for #<Class:0x007fa12bcc8700> (NameError)
/Users/ankur/.rvm/gems/ruby-2.2.2@project/gems/activerecord-5.0.0/lib/active_record/dynamic_matchers.rb:21:in `method_missing'
/Users/ankur/dev/project/project/app/models/bot.rb:2:in `<class:Bot>'
/Users/ankur/dev/project/project/app/models/bot.rb:1:in `<top (required)>'
/Users/ankur/.rvm/gems/ruby-2.2.2@project/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
/Users/ankur/.rvm/gems/ruby-2.2.2@project/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
/Users/ankur/.rvm/gems/ruby-2.2.2@project/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
/Users/ankur/.rvm/gems/ruby-2.2.2@project/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
/Users/ankur/.rvm/gems/ruby-2.2.2@project/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:380:in `block in require_or_load'
/Users/ankur/.rvm/gems/ruby-2.2.2@project/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:37:in `block in load_interlock'
/Users/ankur/.rvm/gems/ruby-2.2.2@project/gems/activesupport-5.0.0/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
/Users/ankur/.rvm/gems/ruby-2.2.2@project/gems/activesupport-5.0.0/lib/active_support/concurrency/share_lock.rb:117:in `exclusive'
/Users/ankur/.rvm/gems/ruby-2.2.2@project/gems/activesupport-5.0.0/lib/active_support/dependencies/interlock.rb:11:in `loading'
/Users/ankur/.rvm/gems/ruby-2.2.2@project/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:37:in `load_interlock'
/Users/ankur/.rvm/gems/ruby-2.2.2@project/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:358:in `require_or_load'
/Users/ankur/.rvm/gems/ruby-2.2.2@project/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:511:in `load_missing_constant'
/Users/ankur/.rvm/gems/ruby-2.2.2@project/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:203:in `const_missing'
/Users/ankur/dev/project/project/spec/factories/bots.rb:2:in `block in <top (required)>'
/Users/ankur/.rvm/gems/ruby-2.2.2@project/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:49:in `instance_eval'
/Users/ankur/.rvm/gems/ruby-2.2.2@project/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:49:in `run'
/Users/ankur/.rvm/gems/ruby-2.2.2@project/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:7:in `define'
/Users/ankur/dev/project/project/spec/factories/bots.rb:1:in `<top (required)>'
```

I have a factory 

```
FactoryGirl.define do
  factory :bot, class: Bot do |f|
    f.name 'Bot'
    f.description { Faker::Lorem.paragraph }

    factory :public_bot do |f|
      f.remote_avatar_url { Faker::Avatar.image }
    end

  end
end
```

**Comment by devilankur18** [comment]
nvm its spring related issue, restarted spring and it worked.
